### ISSUE TITLE
Could not resolve module specifier

### ISSUE THREAD

**Issue by CodyDeeds** [EOSBlox/airDropWebsite#1]
Could not resolve module specifier "@polymer/polymer/polymer-element.js" in file "/home/user/airDropWebsite/src/eos-air-drops-app.js".
Could not resolve module specifier "@polymer/polymer/lib/utils/settings.js" in file "/home/user/airDropWebsite/src/eos-air-drops-app.js".
Could not resolve module specifier "@polymer/iron-ajax/iron-ajax.js" in file "/home/user/airDropWebsite/src/eos-air-drops-app.js".

**Comment by netromdk** [comment]
Hi, @CodyDeeds. It seems you haven't installed the dependencies?
Make sure you do `npm install` and `npm install -g polymer-cli`.

**Comment by CodyDeeds** [comment]
thanks
